"""add tombstones to media and libraries

Revision ID: 013c1be1a485
Revises: b3748691f25c
Create Date: 2026-08-18 23:28:11.600371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '013c1be1a485'
down_revision: Union[str, Sequence[str], None] = 'b3748691f25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_change',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('note', 'library', 'media', 'media_progress', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.Enum('create', 'update', 'delete', name='operation'), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_change_device_id'), 'sync_change', ['device_id'], unique=False)
    op.create_index('ix_sync_change_entity', 'sync_change', ['entity_type', 'entity_id'], unique=False)
    op.add_column('libraries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'deleted_at')
    op.drop_column('libraries', 'deleted_at')
    op.drop_index('ix_sync_change_entity', table_name='sync_change')
    op.drop_index(op.f('ix_sync_change_device_id'), table_name='sync_change')
    op.drop_table('sync_change')
    # ### end Alembic commands ###
