"""add tombstones to media_progress

Revision ID: 29250568b798
Revises: 013c1be1a485
Create Date: 2026-08-18 23:52:05.366360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29250568b798'
down_revision: Union[str, Sequence[str], None] = '013c1be1a485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_progress', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_progress', 'deleted_at')
    # ### end Alembic commands ###
