"""make media duration nullable

Revision ID: 496992d9f177
Revises: 4f4255b5e65c
Create Date: 2026-08-09 17:01:05.089374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "496992d9f177"
down_revision: Union[str, Sequence[str], None] = "4f4255b5e65c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "media", "duration", existing_type=postgresql.INTERVAL(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "media", "duration", existing_type=postgresql.INTERVAL(), nullable=False
    )
    # ### end Alembic commands ###
