"""rename baseVersion to expectedVersion

Revision ID: 4ff54c45ef28
Revises: 9a1624f30ed2
Create Date: 2026-08-26 15:09:52.917307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ff54c45ef28"
down_revision: Union[str, Sequence[str], None] = "9a1624f30ed2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_change",
        sa.Column(
            "expected_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.drop_column("sync_change", "base_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_change",
        sa.Column("base_version", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("sync_change", "expected_version")
    # ### end Alembic commands ###
