"""add version columns to entities

Revision ID: 90f07340897a
Revises: 29250568b798
Create Date: 2026-08-21 19:21:28.303511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f07340897a'
down_revision: Union[str, Sequence[str], None] = '29250568b798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('libraries', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('media', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('media_progress', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('note', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('sync_change', 'base_version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_change', 'base_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('note', 'version')
    op.drop_column('media_progress', 'version')
    op.drop_column('media', 'version')
    op.drop_column('libraries', 'version')
    op.drop_column('device', 'version')
    # ### end Alembic commands ###
