import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Provider } from "./providers";
import { SlideMenu } from "@/components/_home_components/SlideMenu";
import { SyncService } from "./worker/SyncService";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SyncService />
        <Provider>
          <SlideMenu />
          {children}
        </Provider>
      </body>
    </html>
  );
}